name: Deploy Lambda Function
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  AWS_REGION: us-east-2
  PROJECT_NAME: SR.PasswordReset.Api
  DOTNET_VERSION: '8.0.x'
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build with AOT
        run: dotnet publish -c Release -r linux-x64 --self-contained true
          
      - name: Build with SAM
        run: sam build --template-file serverless.template
        
      - name: Deploy with SAM
        run: |
          sam deploy --stack-name starbucks-password-reset \
            --region ${{ env.AWS_REGION }} \
            --s3-bucket lambda-builds-starbucks \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset