version = 0.1
[default.deploy.parameters]
stack_name = "starbucks-password-reset"
resolve_s3 = true
s3_prefix = "starbucks-password-reset"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
